//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CUOIKI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_kiểm_soát_đặt_hàng
    {
        public string Mã_đơn_hàng { get; set; }
        public string Mã_mô_hình { get; set; }
        public Nullable<int> Số_lượng { get; set; }
        public Nullable<int> Đơn_giá { get; set; }
        public Nullable<int> Thành_tiền { get; set; }
    
        public virtual Table_đơn_đặt_hàng Table_đơn_đặt_hàng { get; set; }
        public virtual Table_mô_hình Table_mô_hình { get; set; }
    }
}
