//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CUOIKI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_khách_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_khách_hàng()
        {
            this.Table_đơn_đặt_hàng = new HashSet<Table_đơn_đặt_hàng>();
        }
    
        public string Mã_khách_hàng { get; set; }
        public string Tên_khách_hàng { get; set; }
        public string Địa_chỉ_khách_hàng { get; set; }
        public string Điện_thoại_khách_hàng { get; set; }
        public string Tên_đăng_nhập { get; set; }
        public string Mật_khẩu { get; set; }
        public Nullable<System.DateTime> Ngày_sinh { get; set; }
        public string Giới_tính { get; set; }
        public string Email { get; set; }
        public string Đã_duyệt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_đơn_đặt_hàng> Table_đơn_đặt_hàng { get; set; }
    }
}
