//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CUOIKI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_chủ_đề
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_chủ_đề()
        {
            this.Table_mô_hình = new HashSet<Table_mô_hình>();
        }
    
        public string Mã_chủ_đề { get; set; }
        public string Tên_chủ_đề__tên_phim_____ { get; set; }
        public byte[] Bộ_sưu_tập { get; set; }
    
        public virtual Table_chủ_đề Table_chủ_đề1 { get; set; }
        public virtual Table_chủ_đề Table_chủ_đề2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_mô_hình> Table_mô_hình { get; set; }
    }
}
