//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_CUOIKI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_mô_hình
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_mô_hình()
        {
            this.Table_kiểm_soát_đặt_hàng = new HashSet<Table_kiểm_soát_đặt_hàng>();
        }
    
        public string Mã_mô_hình { get; set; }
        public string Tên_mô_hình { get; set; }
        public string Đơn_vị_tính { get; set; }
        public string Đơn_giá { get; set; }
        public byte[] Hình_minh_họa { get; set; }
        public string Mô_tả { get; set; }
        public string Mã_chủ_đề { get; set; }
        public string Mã_nhà_sản_xuất { get; set; }
        public Nullable<System.DateTime> Ngày_cập_nhật { get; set; }
        public Nullable<int> Số_lượng_bán { get; set; }
        public Nullable<int> Số_lượt_xem { get; set; }
    
        public virtual Table_chủ_đề Table_chủ_đề { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_kiểm_soát_đặt_hàng> Table_kiểm_soát_đặt_hàng { get; set; }
        public virtual Table_nhà_sản_xuất Table_nhà_sản_xuất { get; set; }
    }
}
